#!/usr/bin/env bash

command -v readlink &> /dev/null
if [ "$?" -eq "0" ] ; then
	#shellcheck disable=SC2155
	export curdir="$( cd "$( dirname "$(readlink "${BASH_SOURCE[0]}" || echo "${BASH_SOURCE[0]}" )" )" && pwd )"
else
	#shellcheck disable=SC2155
	export curdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
fi

shift $((OPTIND-1))
[ "$1" = "--" ] && shift

# sinon option par défaut
export _F_FORCE=${_F_FORCE-0}

case "$1" in

	compilenb)
	    sudo ansible-playbook -i hosts playbooks/compile-nbjardins.yml  --vault-password-file .vault_pass 
		;;

	compilecbd84)
	    sudo ansible-playbook -i hosts playbooks/compile-cbd84.yml  --vault-password-file .vault_pass 
		;;

	deploydap) 
    	ansible-playbook -i hosts playbooks/deploy-dujardinaupotager.yml  --vault-password-file .vault_pass  
        ;;

    deploycbd84) 
    	ansible-playbook -i hosts playbooks/deploy-cbd84.yml  --vault-password-file .vault_pass    		
        ;;

	cd) 
	    sudo ansible-playbook -i hosts playbooks/compile-nbjardins.yml  --vault-password-file .vault_pass 
        ansible-playbook -i hosts playbooks/deploy-dujardinaupotager.yml  --vault-password-file .vault_pass 
		;;

    infraremote) 
	    ansible-playbook -i hosts playbooks/install-remote.yml  --vault-password-file .vault_pass 
		;;

	*)
		echo "Utilisation : $0"
		echo "	compilenb : compiler nbjardins"
		echo "	compilecbd84 : compiler cbd84"
		echo "	deploydap : deployer du jardin au potager"
		echo "	deploycbd84 : deployer cbd84"
        echo "	infraremote : installer l'infra remote"
		echo "	cd : compiler et déployer nbjardins"
		;;
esac