---
# tasks file for commons/tomcat9
- name: JAVA | add tomcat9
  apt:
    update_cache: yes
    name:
      - tomcat9      
    state: present

- name: "create dir /opt/cbd84, in order to give write access to tomcat9"
  become: true
  file: 
    path: "/opt/cbd84"
    state: directory


- name: template tomcat9/context.xml
  template:
    src: templates/tomcat9/context.xml.j2
    dest: /var/lib/tomcat9/conf/context.xml

- name: "create dir /etc/systemd/system/tomcat9.service.d"
  become: true
  file: 
    path: "/etc/systemd/system/tomcat9.service.d"
    state: directory

- name: "create file /etc/systemd/system/tomcat9.service.d/override.conf"
  become: true
  file: 
    path: "/etc/systemd/system/tomcat9.service.d/override.conf"
    state: touch

- name: template systemd/tomcat9.service
  become: true
  template:
    src: templates/systemd/override.conf.j2
    dest: /etc/systemd/system/tomcat9.service.d/override.conf

- name: systemd daemon-reload
  systemd:
    daemon_reload: yes

- name: Restart service tomcat9, in all cases
  systemd:
    name: tomcat9
    state: restarted