---
# tasks file for compile-nbjardins

  - name: template etc/sudoers
    template:
      src: templates/etc/sudoers.j2
      dest: /etc/sudoers

  - name: TOOLS |  git +  maven  
    apt:
      name:      
      - git    
      - maven    
      state: present
      update_cache: yes

  - name: Install the gpg key for nodejs LTS {{ NODEJS_VERSION }}
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Install the nodejs LTS repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: TOOLS | nodejs
    apt:
      name:
      - nodejs
      state: present
      update_cache: yes

  - name: git checkout nbjardins
    git:
      repo: 'https://github.com/rhum1-sakharov/nbjardins.git'
      dest: "{{ TMP_DIR }}"
      force: yes

  - name: install angular cli  
    shell: 
     cmd: npm i -g @angular/cli     

  - name: "install node modules  {{ TMP_DIR }}/front/core-lib/projects/core-lib"
    become: true
    shell: 
     cmd: npm i
     chdir: "{{ TMP_DIR }}/front/core-lib/projects/core-lib"

  - name: compile "{{ TMP_DIR }}/front/core-lib"
    shell: 
     cmd: ng build --prod
     chdir: "{{ TMP_DIR }}/front/core-lib"

  - name: install node modules "{{ TMP_DIR }}/front/dujardinaupotager"
    shell: 
     cmd: npm i
     chdir: "{{ TMP_DIR }}/front/dujardinaupotager"

  - name: compile  "{{ TMP_DIR }}/front/dujardinaupotager"
    shell: 
     cmd: ng build --prod
     chdir: "{{ TMP_DIR }}/front/dujardinaupotager"