---
# tasks file for remote/deploy-choralegourmande

- name: "copy chorale-gourmande.jar"
  become: true
  copy:
   src: "{{ TMP_DIR }}/choralegourmande/target/chorale-gourmande.jar"
   dest: "{{ APPLICATION_DIR }}/chorale-gourmande.jar"

- name: "Chmod +x {{ APPLICATION_DIR }}/chorale-gourmande.jar"
  become: true
  file:
    path: "{{ APPLICATION_DIR }}/chorale-gourmande.jar"      
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: '0755'

- name: "create systemd service chorale-gourmande"
  become: true
  template:
    src: templates/chorale-gourmande.service.j2
    dest: "/etc/systemd/system/chorale-gourmande.service"

- name: Enable service chorale-gourmande and ensure it is not masked
  become: true
  systemd:
    name: chorale-gourmande
    enabled: yes
    masked: no

- name: Just force systemd to reread configs (2.4 and above)
  become: true
  systemd:
    daemon_reload: yes

- name: start service chorale-gourmande, in all cases
  become: true
  systemd:
    name: chorale-gourmande
    state: started

- name: "mkdir  {{ APPLICATION_DIR }}/config"
  become: true
  file: 
    path: "{{ APPLICATION_DIR }}/config"
    state: directory
  
- name: "add application.yml"
  become: true
  template:
    src: templates/application.yml.j2
    dest: "{{ APPLICATION_DIR }}/config/application.yml"
    backup: yes

  
- name: "remove dir {{ WEB_APPLICATION_DIR }}"
  become: true
  file: 
    path: "{{ WEB_APPLICATION_DIR }}"
    state: absent

- name: "create dir {{ WEB_APPLICATION_DIR }}"
  become: true
  file:   
    path: "{{ WEB_APPLICATION_DIR }}"
    state: directory
  

- name: template chorale-gourmande.conf for apache2
  become: true
  template:
    src: templates/chorale-gourmande.conf.j2
    dest: /etc/apache2/sites-enabled/chorale-gourmande.conf

- name: ".htaccess for {{ WEB_APPLICATION_DIR }}"
  become: true
  template:
    src: templates/htaccess.j2
    dest: "{{ WEB_APPLICATION_DIR }}/.htaccess"

- name: "copy files"
  become: true
  copy:
    src: "{{ LOCAL_DIST }}/"
    dest: "{{ WEB_APPLICATION_DIR }}"

- name: Restart service apache2, in all cases
  become: true
  service:
    name: apache2
    state: restarted    