---
# tasks file for java
- name: "JAVA | add openjdk version {{ openjdk_version }}"
  apt:
    update_cache: yes
    name:
      - openjdk-{{ openjdk_version }}-jdk
      - openjdk-{{ openjdk_version }}-jdk-headless
    state: present

- name: JAVA | add maven
  apt:
    update_cache: yes
    name:
      - maven      
    state: present

- name: JAVA | add tomcat9
  apt:
    update_cache: yes
    name:
      - tomcat9      
    state: present