---
- name: Compiler le projet nbjardins
  hosts: localhost
  connection: local  
  become: true 
  vars:
    NODEJS_VERSION: "12"
    ansible_distribution_release: "focal" #trusty
    TMP_DIR: "/tmp/nbjardins"
    WEB_APPLICATION_DIR: "/var/www/nbjardins"
    APPLICATION_DIR: "/opt/nbjardins"
    BACK_PORT: "8060"
  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE ROLE | compile-nbjardins    
    include_role:      
      name: compile-nbjardins  
  