---  
- name: Compiler le projet chorale gourmande
  hosts: localhost
  connection: local  
  become: true 
  vars:    
    ansible_distribution_release: "focal" #trusty
    TMP_DIR: "/tmp/choralegourmande"   
    APPLICATION_DIR: "/opt/choralegourmande"
    BACK_PORT: "8090"
  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE | commons/tools    
    include_role:      
      name: commons/tools

  - name: INCLUDE | commons/java    
    include_role:      
      name: commons/java 

  - name: INCLUDE | local/compile-choralegourmande    
    include_role:      
      name: local/compile-choralegourmande  
  