---
- name: "Deploiement de l'application du jardin au potager"
  hosts: webservers   
  become: true
  remote_user: root  
  vars:    
    WEB_APPLICATION_DIR: "/var/www/dujardinaupotager" 
    LOCAL_DIST: "/tmp/nbjardins/front/dujardinaupotager/dist/dujardinaupotager"
    

  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE | remote/deploy-dujardinaupotager
    include_role:      
      name: remote/deploy-dujardinaupotager  
  