---
- name: "Deploiement de l'application cbd84"
  hosts: webservers   
  become: true
  remote_user: root  
  vars:    
    WEB_APPLICATION_DIR: "/var/lib/tomcat9/webapps" 
    LOCAL_DIST: "/tmp/cbd84/target"
    

  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE | remote/deploy-cbd84
    include_role:      
      name: remote/deploy-cbd84
  