---
- name: Deploiement de l'application nbjardins
  hosts: webservers   
  remote_user: root
  vars:
    NODEJS_VERSION: "12"
    ansible_distribution_release: "bionic" #trusty
    TMP_DIR: "/tmp/nbjardins"
    WEB_APPLICATION_DIR: "/var/www/nbjardins"
    APPLICATION_DIR: "/opt/nbjardins"
    BACK_PORT: "8060"
  
  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE | remote/nbjardins
    include_role:      
      name: remote/nbjardins  
  