---
- name: "Deploiement de l'application du jardin au potager"
  hosts: all   
  become: true
  remote_user: root  
  vars:    
    WEB_APPLICATION_DIR: "/var/www/dujardinaupotager" 
    

  tasks:  

  - name: INCLUDE | vars.yml
    include_vars: vars.yml

  - name: INCLUDE ROLE | deploy-dujardinaupotager
    include_role:      
      name: deploy-dujardinaupotager  
  