---
# tasks file for remote/deploy-cbd84

- name: stop service tomcat9, in all cases
  become: true
  systemd:
    name: tomcat9
    state: stopped

- name: "remove dir {{ WEB_APPLICATION_DIR }}/cbd84"
  file: 
    path: "{{ WEB_APPLICATION_DIR }}/cbd84"
    state: absent

- name: "remove dir {{ WEB_APPLICATION_CACHE }}"
  become: true
  file: 
    path: "{{ WEB_APPLICATION_CACHE }}"
    state: absent

- name: "Change file ownership, group and permissions for {{ WEB_DATA_DIR }}"
  file:
    path: "{{ WEB_DATA_DIR }}"
    state: directory
    recurse: yes
    owner: "tomcat"
    group: "tomcat"
    mode: '0777'    


- name: "create dir {{ WEB_DATA_DIR }}/data"
  file: 
    path: "{{ WEB_DATA_DIR }}/data"
    state: directory


- name: "remove war {{ WEB_APPLICATION_DIR }}/cbd84.war"
  file: 
    path: "{{ WEB_APPLICATION_DIR }}/cbd84.war"
    state: absent
  
- name: "copy cbd84.war"
  copy:
    src: "{{ LOCAL_DIST }}/cbd84.war"
    dest: "{{ WEB_APPLICATION_DIR }}/"



- name: template cbd84.conf for apache2
  template:
    src: templates/cbd84.conf.j2
    dest: /etc/apache2/sites-enabled/cbd84.conf

- name: template tomcat9/server.xml for tomcat9
  template:
    src: templates/tomcat9/server.xml.j2
    dest: /var/lib/tomcat9/conf/server.xml

- name: Restart service tomcat9, in all cases
  service:
    name: tomcat9
    state: restarted

- name: Restart service apache2, in all cases
  service:
    name: apache2
    state: restarted